### ISSUE TITLE
No tests run

### ISSUE THREAD

**Issue by joshblum** [lamby/django-template-tests#1]
No extra tests seem to be run after I add `template_tests` to `INSTALLED_APPS`, is there a setting that I'm missing?

**Comment by lamby** [comment]
Please paste the output of

```
from template_tests.utils import get_template_dirs
list(get_template_dirs())
```

**Comment by joshblum** [comment]
```
In [1]: from template_tests.utils import get_template_dirs

In [2]: list(get_template_dirs())
Out[2]: ['/website/templates']
```

**Comment by lamby** [comment]
.. and are there templates under there? :p  Look at where get_template_dirs is called and add a few print statements..

**Comment by joshblum** [comment]
yup :) i ran this, so it's definitely able to fine them, however it doesn't appear to run at all (number of tests remains unchanged when I run `./manage.py test`

```
In [7]: for x in get_template_dirs():

    for root, _, templates in os.walk(x):
        for y in templates:
            print(y)
   ...:             
index.html
```

**Comment by lamby** [comment]
Is the metaclass adding the test_ methods though? I don't know where it is breaking for you, sorry. 

On Sat, 2 Apr 2016, at 07:40 PM, Joshua Blum wrote:

> yup :) i ran this, so it's definitely able to fine them, however it doesn't appear to run at all (number of tests remains unchanged when I run `./manage.py test`
> 
> ```
> In [7]: for x in get_template_dirs():
> 
>     for root, _, templates in os.walk(x):
>         for y in templates:
>             print(y)
>    ...:             
> index.html
> ```
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/lamby/django-template-tests/issues/1#issuecomment-204771148

## 

Chris Lamb
chris-lamb.co.uk / @lolamby

**Comment by joshblum** [comment]
Meta class never seems to be called :( I copied the files directly into my project structure (since I think my test runner ignores 3rd party apps (separate issue to deal with later)) but no tests run :( I put an `assert False` in the `__new__` method of the metaclass but it never gets hit

```
$ ./manage.py test common.tests.test_templates
Creating test database for alias 'default'...

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Destroying test database for alias 'default'...
```

**Comment by lamby** [comment]
> `common.tests.test_templates`

Huh? Exactly what test are you trying to run here?

> my test runner ignores 3rd party apps 

Makes me suspicious that this is the issue. Just cannot reproduce this, sorry.

**Comment by joshblum** [comment]
I copied the testing code into a file in one of my apps, the `TestTemplates` class is called, however the `TestTemplatesMeta.__new__` is not. This make's me think it is on your end, not mine

**Comment by lamby** [comment]
You are using Python 3.
